import type { Metadata } from "next";
import { notFound } from "next/navigation";
const pages: Record<string, { title: string; intro: string; sections: { title: string; body: string }[] }> = {
  faq: { title: "Perguntas frequentes", intro: "Respostas gerais sobre compras e serviços.", sections: [{ title: "Como confirmar um agendamento?", body: "Após preencher o formulário, envie o resumo para o WhatsApp. A equipe confirma disponibilidade, serviço e valor." }, { title: "Posso retirar na loja?", body: "Sim. A retirada aparece como opção no checkout. O pedido deve ser confirmado antes do deslocamento." }, { title: "Vocês fazem entrega?", body: "A plataforma está preparada para entrega, mas área atendida, prazo e preço precisam ser configurados pela empresa." }] },
  privacidade: { title: "Política de privacidade", intro: "Modelo de estrutura — requer revisão jurídica e preenchimento antes do lançamento.", sections: [{ title: "Dados coletados", body: "A plataforma pode coletar dados de contato, endereço, pedidos, pets e agendamentos estritamente para prestar os serviços solicitados." }, { title: "Uso e segurança", body: "Dados devem ser usados apenas para atendimento, operação, prevenção de fraude e obrigações legais, com acesso restrito." }, { title: "Seus direitos", body: "O canal e o responsável pelo tratamento de dados precisam ser definidos pela empresa antes da publicação." }] },
  termos: { title: "Termos de uso", intro: "Conteúdo-base sujeito a validação jurídica.", sections: [{ title: "Uso da plataforma", body: "Preços, estoque, horários e serviços são validados no momento da confirmação." }, { title: "Pagamentos", body: "O site não armazena dados de cartão. O processamento deve ocorrer no ambiente seguro do provedor configurado." }] },
  trocas: { title: "Trocas e devoluções", intro: "Regras comerciais pendentes de confirmação.", sections: [{ title: "Solicitação", body: "Prazos, condições e canal oficial de troca devem ser definidos pela Patinhas Pet Center antes do lançamento." }, { title: "Produtos de saúde", body: "Podem existir restrições específicas conforme a natureza e integridade do produto, sempre respeitando a legislação aplicável." }] },
  entrega: { title: "Política de entrega", intro: "Modalidades previstas: retirada na loja e entrega.", sections: [{ title: "Retirada", body: "A retirada ocorrerá no endereço da loja após confirmação do pedido." }, { title: "Entrega", body: "Área atendida, prazos, transportador e cálculo de frete precisam ser configurados." }] },
};
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const page = pages[(await params).slug]; return { title: page?.title ?? "Informação" }; }
export default async function LegalPage({ params }: { params: Promise<{ slug: string }> }) { const page = pages[(await params).slug]; if (!page) notFound(); return <main><section className="page-hero"><div className="shell"><span className="eyebrow">Informações</span><h1>{page.title}</h1><p>{page.intro}</p></div></section><section className="section"><article className="shell legal">{page.sections.map((section) => <section key={section.title}><h2>{section.title}</h2><p>{section.body}</p></section>)}</article></section></main>; }
