import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { Check, ShieldCheck, Star, Truck } from "lucide-react";
import { ProductPurchase } from "@/components/product-purchase";
import { ProductCard } from "@/components/product-card";
import { formatPrice, getProduct, products } from "@/lib/catalog";
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const product = getProduct(slug); return product ? { title: product.name, description: product.description } : { title: "Produto não encontrado" }; }
export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const product = getProduct(slug); if (!product) notFound();
  const visualStyle = { "--swatch": product.color, "--image-position": product.imagePosition } as React.CSSProperties;
  const related = products.filter((item) => item.id !== product.id && (item.category === product.category || item.animal === product.animal)).slice(0, 4);
  return <main><section className="section"><div className="shell"><div className="mb-8 text-sm text-[#766f6d]"><Link href="/">Início</Link> / <Link href="/loja">Loja</Link> / {product.name}</div><div className="product-detail"><div className="product-gallery" style={visualStyle}><div className="product-detail-photo" role="img" aria-label={product.imageAlt} /></div><div className="product-detail-card"><span className="eyebrow">{product.category} · {product.animal}</span><h1>{product.name}</h1><div className="flex items-center gap-3 text-sm"><span className="flex gap-0.5 text-[#e5a800]"><Star fill="currentColor" /><Star fill="currentColor" /><Star fill="currentColor" /><Star fill="currentColor" /><Star /></span><span className="text-[#77706c]">Produto demonstrativo</span></div>{product.oldPrice && <div className="mt-6 text-sm text-[#958c87] line-through">{formatPrice(product.oldPrice)}</div>}<div className={product.oldPrice ? "detail-price" : "mt-6 detail-price"}>{formatPrice(product.price)}</div><p className="mt-1 text-sm text-[#756e6b]">Imagem ilustrativa. Confirme preço e disponibilidade com a equipe.</p><div className="mt-6 detail-note"><strong>Sobre o produto:</strong> {product.description}</div><div className="mt-5 grid gap-3 text-sm"><span className="flex items-center gap-2"><Check className="size-4 text-[#8b1937]" />Marca: {product.brand}</span><span className="flex items-center gap-2"><Check className="size-4 text-[#8b1937]" />Variação: {product.size}</span><span className="flex items-center gap-2"><Check className="size-4 text-[#8b1937]" />Estoque demonstrativo: {product.stock ?? "consultar"}</span></div><ProductPurchase product={product} /><div className="mt-6 grid grid-cols-2 gap-3"><div className="detail-note flex items-center gap-2"><Truck className="size-5" />Entrega ou retirada</div><div className="detail-note flex items-center gap-2"><ShieldCheck className="size-5" />Compra protegida</div></div></div></div></div></section><section className="section section-soft"><div className="shell"><div className="section-heading"><div><span className="eyebrow">Combine com</span><h2>Produtos relacionados</h2></div></div><div className="product-grid">{related.map((item) => <ProductCard product={item} key={item.id} />)}</div></div></section></main>;
}
