import { env } from "cloudflare:workers";
export const dynamic = "force-dynamic";
function hex(buffer: ArrayBuffer) { return [...new Uint8Array(buffer)].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
async function validSignature(request: Request, dataId: string) {
  const secret = (env as unknown as Record<string, string>).MERCADO_PAGO_WEBHOOK_SECRET; if (!secret) return false; const signature = request.headers.get("x-signature") ?? ""; const requestId = request.headers.get("x-request-id") ?? ""; const parts = Object.fromEntries(signature.split(",").map((part) => part.trim().split("="))); const ts = parts.ts; const provided = parts.v1; if (!ts || !provided) return false; const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); const manifest = `id:${dataId};request-id:${requestId};ts:${ts};`; const expected = hex(await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(manifest))); return expected === provided;
}
export async function POST(request: Request) {
  const url = new URL(request.url); const body = await request.clone().json().catch(() => ({})) as { data?: { id?: string | number } }; const dataId = String(body.data?.id ?? url.searchParams.get("data.id") ?? ""); if (!dataId || !(await validSignature(request, dataId))) return Response.json({ error: "Assinatura inválida" }, { status: 401 });
  const token = (env as unknown as Record<string, string>).MERCADO_PAGO_ACCESS_TOKEN; if (!token) return Response.json({ error: "Gateway não configurado" }, { status: 503 }); const response = await fetch(`https://api.mercadopago.com/v1/payments/${encodeURIComponent(dataId)}`, { headers: { authorization: `Bearer ${token}` } }); if (!response.ok) return Response.json({ error: "Pagamento não encontrado" }, { status: 404 }); const payment = await response.json() as { id: number; status: string; status_detail?: string; external_reference?: string }; if (!payment.external_reference) return Response.json({ ok: true });
  const status = payment.status === "approved" ? "paid" : payment.status === "cancelled" || payment.status === "rejected" ? "payment_failed" : "pending_payment"; await env.DB.batch([env.DB.prepare("UPDATE payments SET status = ?, raw_status = ? WHERE provider_payment_id = ?").bind(payment.status, payment.status_detail ?? null, String(payment.id)), env.DB.prepare("UPDATE orders SET status = ? WHERE id = ?").bind(status, payment.external_reference)]); return Response.json({ ok: true });
}
