import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Bath, CalendarDays, HeartHandshake, MapPin, MessageCircle, PackageCheck, Scissors, ShieldCheck, ShoppingBag, Sparkles, Star, Truck } from "lucide-react";
import { CategoryGrid } from "@/components/category-grid";
import { ProductCard } from "@/components/product-card";
import { products, store } from "@/lib/catalog";

export default function Home() {
  const schema = { "@context": "https://schema.org", "@type": "PetStore", name: store.name, address: { "@type": "PostalAddress", streetAddress: "Rua Francisco Antônio dos Santos, 388", addressLocality: "Lavras", addressRegion: "MG", postalCode: "37203-750", addressCountry: "BR" }, telephone: "+55 35 98842-7974", sameAs: [`https://instagram.com/${store.instagram}`] };
  return <main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <section className="hero"><div className="hero-content shell"><div className="hero-copy reveal"><span className="eyebrow">Pet shop completo em Lavras</span><h1>Todo carinho que o seu pet <em>merece.</em></h1><p>Produtos, farmácia pet e banho e tosa em um só lugar — com atendimento próximo e a confiança de quem cuida desde 2015.</p><div className="hero-actions"><Link className="btn btn-primary btn-lg" href="/loja"><ShoppingBag />Comprar produtos</Link><Link className="btn btn-outline btn-lg" href="/agendar"><CalendarDays />Agendar banho e tosa</Link></div><div className="trust-row"><span><ShieldCheck />Compra segura</span><span><MapPin />Lavras, MG</span><span><MessageCircle />Atendimento no WhatsApp</span></div></div></div></section>
    <section className="section"><div className="shell"><div className="section-heading"><div><span className="eyebrow">Encontre por pet</span><h2>Feito para cada patinha</h2></div><p>Da alimentação ao cuidado diário, encontre as categorias identificadas na loja e fale com a equipe quando precisar de orientação.</p></div><CategoryGrid /></div></section>
    <section className="section section-soft"><div className="shell"><div className="section-heading"><div><span className="eyebrow">Achadinhos da Patinhas</span><h2>Destaques da loja</h2></div><Link href="/loja" className="btn btn-outline">Ver catálogo completo <ArrowRight /></Link></div><div className="product-grid">{products.slice(0, 4).map((product) => <ProductCard key={product.id} product={product} />)}</div><p className="notice mt-6">Os preços exibidos são apenas os que puderam ser identificados nas imagens enviadas. Pesos, variações e estoque devem ser confirmados antes da compra.</p></div></section>
    <section className="section"><div className="shell image-split"><div className="image-frame aspect-[1.25]"><Image src="/images/interior-patinhas.png" alt="Interior da Patinhas Pet Center com balcão, acessórios e farmácia pet" fill sizes="(max-width: 820px) 100vw, 55vw" /></div><div className="story-copy"><span className="eyebrow">Loja renovada</span><h2>Um pet center pensado para cuidar bem.</h2><p>A Patinhas reúne alimentação, brinquedos, acessórios, higiene, suplementos e farmácia pet em um ambiente organizado e acolhedor.</p><div className="facts"><div className="fact"><strong>Desde 2015</strong><span>experiência local</span></div><div className="fact"><strong>Lavras</strong><span>atendimento próximo</span></div><div className="fact"><strong>Pet completo</strong><span>loja + serviços</span></div></div><Link href="/sobre" className="btn btn-dark">Conheça a Patinhas <ArrowRight /></Link></div></div></section>
    <section className="section pt-0"><div className="shell service-band"><div className="service-band-inner"><div className="service-copy"><span className="eyebrow text-[#f3b91f]">Banho & Tosa</span><h1>Um momento de cuidado, sem complicação.</h1><p className="!text-white/60">Agende online, escolha o serviço e receba o resumo pronto para confirmar pelo WhatsApp.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/agendar" className="btn btn-gold">Agendar agora <ArrowRight /></Link><Link href="/banho-e-tosa" className="btn border-white/20 bg-white/10 text-white">Conhecer serviços</Link></div></div><div className="service-list"><div className="service-chip"><span className="service-chip-icon"><Bath /></span><h3>Banho</h3><p>Higiene com avaliação do perfil do pet.</p></div><div className="service-chip"><span className="service-chip-icon"><Scissors /></span><h3>Tosa</h3><p>Cuidado da pelagem com atendimento profissional.</p></div><div className="service-chip"><span className="service-chip-icon"><Sparkles /></span><h3>Banho + Tosa</h3><p>Experiência completa em uma única visita.</p></div></div></div></div></section>
    <section className="section section-soft"><div className="shell"><div className="section-heading"><div><span className="eyebrow">Por que escolher</span><h2>Do clique ao carinho</h2></div></div><div className="benefit-grid"><div className="benefit"><PackageCheck /><strong>Tudo para seu pet</strong><span>Mix amplo na loja</span></div><div className="benefit"><Bath /><strong>Banho e tosa</strong><span>Agendamento online</span></div><div className="benefit"><Truck /><strong>Entrega ou retirada</strong><span>Escolha no checkout</span></div><div className="benefit"><ShieldCheck /><strong>Compra segura</strong><span>Pagamento protegido</span></div><div className="benefit"><HeartHandshake /><strong>Atendimento humano</strong><span>Fale pelo WhatsApp</span></div></div></div></section>
    <section className="section"><div className="shell"><div className="section-heading"><div><span className="eyebrow">@patinhas_petcenter</span><h2>Vida real, cuidado de verdade</h2></div><a href={`https://instagram.com/${store.instagram}`} className="btn btn-outline" target="_blank" rel="noreferrer">Seguir no Instagram <ArrowRight /></a></div><div className="instagram-strip"><div className="insta-card"><Image src="/images/fachada-patinhas.png" alt="Fachada preta e amarela da Patinhas Pet Center" fill sizes="25vw" /><span>Nossa loja</span></div><div className="insta-card"><Image src="/images/interior-patinhas.png" alt="Interior da loja" fill sizes="25vw" /><span>Farmácia pet</span></div><div className="insta-card"><Image src="/images/hero-patinhas.png" alt="Cachorro e gato na loja" fill sizes="25vw" /><span>Achadinhos</span></div><div className="insta-card grid place-items-center bg-[#f3b91f] p-8 text-center"><div><Star className="mx-auto mb-4 size-10" /><strong className="block font-serif text-3xl">11 anos</strong><span className="!static !text-[#17151a] !shadow-none">de histórias com pets e famílias</span></div></div></div></div></section>
  </main>;
}
