"use client";
import Link from "next/link";
import { Minus, PackageOpen, Plus, ShoppingBag, Trash2 } from "lucide-react";
import { useCart } from "@/components/cart-provider";
import { formatPrice, products } from "@/lib/catalog";
export function CartPageClient() {
  const { items, subtotal, update, remove, loading } = useCart();
  if (loading) return <div className="empty-state">Carregando seu carrinho...</div>;
  if (!items.length) return <div className="empty-state"><ShoppingBag className="mx-auto size-10 text-[#8b1937]" /><h2 className="mt-4 font-serif text-3xl font-bold">Seu carrinho está esperando.</h2><p className="mt-2 text-[#766f6d]">Escolha um achadinho para seu pet.</p><Link href="/loja" className="btn btn-primary mt-6">Ir para a loja</Link></div>;
  return <div className="cart-layout"><div className="form-card"><h2 className="font-serif text-3xl font-bold">Produtos</h2>{items.map((item) => { const product = products.find((candidate) => candidate.id === item.productId); if (!product) return null; return <article className="cart-item" key={item.productId}><div className="cart-thumb" style={{ background: product.color }}><PackageOpen /></div><div><strong>{product.name}</strong><p className="mt-1 text-xs text-[#766f6d]">{product.brand} · {product.size}</p><div className="quantity mt-4"><button onClick={() => update(item.productId, item.quantity - 1)} aria-label="Diminuir"><Minus /></button><strong>{item.quantity}</strong><button onClick={() => update(item.productId, item.quantity + 1)} aria-label="Aumentar"><Plus /></button></div></div><div className="text-right"><strong>{formatPrice((product.price ?? 0) * item.quantity)}</strong><button className="mt-4 flex items-center gap-1 text-xs text-[#8b1937]" onClick={() => remove(item.productId)}><Trash2 className="size-3" />Remover</button></div></article>; })}</div><aside className="summary-card"><h2 className="font-serif text-2xl font-bold">Resumo do pedido</h2><div className="mt-5"><div className="summary-line"><span>Subtotal</span><strong>{formatPrice(subtotal)}</strong></div><div className="summary-line"><span>Entrega</span><strong>Calculada no checkout</strong></div><div className="summary-line !border-0 text-lg"><span>Total parcial</span><strong>{formatPrice(subtotal)}</strong></div></div><Link href="/checkout" className="btn btn-primary btn-lg mt-5 w-full">Ir para o checkout</Link><Link href="/loja" className="btn btn-outline mt-3 w-full">Continuar comprando</Link><p className="notice mt-5">Preços, estoque e descontos são revalidados no servidor antes da criação do pedido.</p></aside></div>;
}
