"use client";
import { useMemo, useState } from "react";
import { Search, SlidersHorizontal } from "lucide-react";
import { ProductCard } from "@/components/product-card";
import { products } from "@/lib/catalog";
type Sort = "destaques" | "menor" | "maior" | "recentes";
export function ShopCatalog({ initialQuery = "", initialAnimal = "", onlyOffers = false }: { initialQuery?: string; initialAnimal?: string; onlyOffers?: boolean }) {
  const [query, setQuery] = useState(initialQuery); const [animal, setAnimal] = useState(initialAnimal); const [category, setCategory] = useState(""); const [brand, setBrand] = useState(""); const [onlyPromo, setOnlyPromo] = useState(onlyOffers); const [sort, setSort] = useState<Sort>("destaques");
  const filtered = useMemo(() => {
    let result = products.filter((product) => (!query || `${product.name} ${product.brand} ${product.category}`.toLowerCase().includes(query.toLowerCase())) && (!animal || product.animal === animal) && (!category || product.category === category) && (!brand || product.brand === brand) && (!onlyPromo || !!product.badge));
    if (sort === "menor") result = [...result].sort((a, b) => (a.price ?? Infinity) - (b.price ?? Infinity));
    if (sort === "maior") result = [...result].sort((a, b) => (b.price ?? -1) - (a.price ?? -1));
    if (sort === "recentes") result = [...result].reverse();
    return result;
  }, [query, animal, category, brand, onlyPromo, sort]);
  const categories = [...new Set(products.map((product) => product.category))]; const brands = [...new Set(products.map((product) => product.brand))];
  return <div className="shop-layout"><aside className="filters"><div className="flex items-center gap-2 pb-4"><SlidersHorizontal className="size-4" /><strong>Filtros</strong></div><div className="filter-group"><h3>Animal</h3>{["", "Cachorros", "Gatos", "Outros pets"].map((value) => <label className="filter-option" key={value || "todos"}><input type="radio" name="animal" checked={animal === value} onChange={() => setAnimal(value)} />{value || "Todos"}</label>)}</div><div className="filter-group"><h3>Categoria</h3><select className="control" value={category} onChange={(event) => setCategory(event.target.value)}><option value="">Todas</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></div><div className="filter-group"><h3>Marca</h3><select className="control" value={brand} onChange={(event) => setBrand(event.target.value)}><option value="">Todas</option>{brands.map((item) => <option key={item}>{item}</option>)}</select></div><div className="filter-group"><label className="filter-option"><input type="checkbox" checked={onlyPromo} onChange={(event) => setOnlyPromo(event.target.checked)} />Somente ofertas</label></div></aside><div><div className="shop-toolbar"><label className="search-field flex-1"><Search className="size-5" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por nome, marca ou categoria" /></label><select className="control !w-auto" value={sort} onChange={(event) => setSort(event.target.value as Sort)} aria-label="Ordenar produtos"><option value="destaques">Destaques</option><option value="menor">Menor preço</option><option value="maior">Maior preço</option><option value="recentes">Mais recentes</option></select></div><p className="mb-5 text-sm text-[#766f6d]">{filtered.length} produto{filtered.length === 1 ? "" : "s"} encontrado{filtered.length === 1 ? "" : "s"}</p>{filtered.length ? <div className="product-grid !grid-cols-1 md:!grid-cols-2 xl:!grid-cols-3">{filtered.map((product) => <ProductCard key={product.id} product={product} />)}</div> : <div className="empty-state"><h2>Nenhum produto encontrado</h2><p className="mt-2 text-sm text-[#766f6d]">Tente remover algum filtro ou buscar outro termo.</p></div>}</div></div>;
}
