import { sql } from "drizzle-orm";
import { integer, real, sqliteTable, text, uniqueIndex, index } from "drizzle-orm/sqlite-core";

const createdAt = text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`);
export const users = sqliteTable("users", { id: text("id").primaryKey(), email: text("email").notNull(), name: text("name"), role: text("role").notNull().default("customer"), createdAt }, (table) => [uniqueIndex("idx_users_email").on(table.email)]);
export const pets = sqliteTable("pets", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id), name: text("name").notNull(), type: text("type").notNull(), breed: text("breed"), size: text("size"), age: text("age"), notes: text("notes"), createdAt }, (table) => [index("idx_pets_user_id").on(table.userId)]);
export const addresses = sqliteTable("addresses", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id), label: text("label").notNull().default("Principal"), cep: text("cep").notNull(), street: text("street").notNull(), number: text("number").notNull(), complement: text("complement"), district: text("district").notNull(), city: text("city").notNull(), state: text("state").notNull(), createdAt }, (table) => [index("idx_addresses_user_id").on(table.userId)]);
export const categories = sqliteTable("categories", { id: text("id").primaryKey(), name: text("name").notNull(), slug: text("slug").notNull(), active: integer("active", { mode: "boolean" }).notNull().default(true), createdAt }, (table) => [uniqueIndex("idx_categories_slug").on(table.slug)]);
export const products = sqliteTable("products", { id: text("id").primaryKey(), categoryId: text("category_id").references(() => categories.id), name: text("name").notNull(), slug: text("slug").notNull(), brand: text("brand").notNull(), animal: text("animal").notNull(), description: text("description").notNull(), priceCents: integer("price_cents"), oldPriceCents: integer("old_price_cents"), stock: integer("stock"), active: integer("active", { mode: "boolean" }).notNull().default(true), badge: text("badge"), createdAt }, (table) => [uniqueIndex("idx_products_slug").on(table.slug), index("idx_products_category_id").on(table.categoryId), index("idx_products_brand").on(table.brand)]);
export const productVariants = sqliteTable("product_variants", { id: text("id").primaryKey(), productId: text("product_id").notNull().references(() => products.id), name: text("name").notNull(), sku: text("sku"), priceCents: integer("price_cents"), stock: integer("stock"), active: integer("active", { mode: "boolean" }).notNull().default(true), createdAt }, (table) => [index("idx_product_variants_product_id").on(table.productId), uniqueIndex("idx_product_variants_sku").on(table.sku)]);
export const carts = sqliteTable("carts", { id: text("id").primaryKey(), userId: text("user_id").notNull(), status: text("status").notNull().default("active"), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`), createdAt }, (table) => [uniqueIndex("idx_carts_user_status").on(table.userId, table.status)]);
export const cartItems = sqliteTable("cart_items", { id: integer("id").primaryKey({ autoIncrement: true }), cartId: text("cart_id").notNull().references(() => carts.id), productId: text("product_id").notNull(), quantity: integer("quantity").notNull().default(1), createdAt }, (table) => [uniqueIndex("idx_cart_items_cart_product").on(table.cartId, table.productId)]);
export const orders = sqliteTable("orders", { id: text("id").primaryKey(), orderNumber: text("order_number").notNull(), userId: text("user_id").notNull(), customerName: text("customer_name").notNull(), customerEmail: text("customer_email").notNull(), customerPhone: text("customer_phone").notNull(), deliveryMethod: text("delivery_method").notNull(), addressJson: text("address_json"), paymentMethod: text("payment_method").notNull(), status: text("status").notNull().default("pending"), subtotalCents: integer("subtotal_cents").notNull(), shippingCents: integer("shipping_cents"), totalCents: integer("total_cents").notNull(), createdAt }, (table) => [uniqueIndex("idx_orders_number").on(table.orderNumber), index("idx_orders_user_id").on(table.userId), index("idx_orders_status").on(table.status)]);
export const orderItems = sqliteTable("order_items", { id: integer("id").primaryKey({ autoIncrement: true }), orderId: text("order_id").notNull().references(() => orders.id), productId: text("product_id").notNull(), productName: text("product_name").notNull(), quantity: integer("quantity").notNull(), unitPriceCents: integer("unit_price_cents").notNull(), totalCents: integer("total_cents").notNull() }, (table) => [index("idx_order_items_order_id").on(table.orderId)]);
export const payments = sqliteTable("payments", { id: text("id").primaryKey(), orderId: text("order_id").notNull().references(() => orders.id), provider: text("provider").notNull(), providerPaymentId: text("provider_payment_id"), idempotencyKey: text("idempotency_key").notNull(), status: text("status").notNull().default("pending"), amountCents: integer("amount_cents").notNull(), rawStatus: text("raw_status"), createdAt }, (table) => [uniqueIndex("idx_payments_idempotency").on(table.idempotencyKey), index("idx_payments_provider_id").on(table.providerPaymentId)]);
export const services = sqliteTable("services", { id: text("id").primaryKey(), name: text("name").notNull(), description: text("description").notNull(), priceCents: integer("price_cents"), durationMinutes: integer("duration_minutes").notNull(), acceptedSizes: text("accepted_sizes").notNull().default("Pequeno,Médio,Grande"), active: integer("active", { mode: "boolean" }).notNull().default(true), createdAt });
export const appointments = sqliteTable("appointments", { id: text("id").primaryKey(), userId: text("user_id").notNull(), petName: text("pet_name").notNull(), petType: text("pet_type").notNull(), breed: text("breed"), size: text("size").notNull(), age: text("age"), notes: text("notes"), serviceId: text("service_id").notNull(), date: text("date").notNull(), time: text("time").notNull(), professionalId: text("professional_id").notNull().default("equipe-1"), customerName: text("customer_name").notNull(), phone: text("phone").notNull(), email: text("email").notNull(), status: text("status").notNull().default("pending"), createdAt }, (table) => [uniqueIndex("idx_appointments_slot").on(table.date, table.time, table.professionalId), index("idx_appointments_date_status").on(table.date, table.status), index("idx_appointments_user_id").on(table.userId)]);
export const schedules = sqliteTable("schedules", { id: text("id").primaryKey(), weekday: integer("weekday").notNull(), startTime: text("start_time").notNull(), endTime: text("end_time").notNull(), intervalMinutes: integer("interval_minutes").notNull().default(60), capacity: integer("capacity").notNull().default(1), active: integer("active", { mode: "boolean" }).notNull().default(true) }, (table) => [uniqueIndex("idx_schedules_weekday_start").on(table.weekday, table.startTime)]);
export const blockedSlots = sqliteTable("blocked_slots", { id: text("id").primaryKey(), date: text("date").notNull(), time: text("time"), reason: text("reason"), createdAt }, (table) => [index("idx_blocked_slots_date").on(table.date)]);
