import { env } from "cloudflare:workers";
import { z } from "zod";
import { products } from "@/lib/catalog";
export const dynamic = "force-dynamic";
const schema = z.object({ customer: z.object({ name: z.string().min(2), email: z.string().email(), phone: z.string().min(8), cep: z.string(), street: z.string(), number: z.string(), complement: z.string().optional(), district: z.string(), city: z.string(), state: z.string().length(2), delivery: z.enum(["retirada", "entrega"]), payment: z.enum(["pix", "card"]) }), items: z.array(z.object({ productId: z.string(), quantity: z.number().int().min(1).max(99) })).min(1) });
export async function POST(request: Request) {
  try { if (!env.DB) throw new Error("DB unavailable"); const input = schema.parse(await request.json()); const validated = input.items.map((item) => { const product = products.find((candidate) => candidate.id === item.productId); if (!product || product.price === null) throw new Error("Produto indisponível"); return { ...item, product, unitCents: Math.round(product.price * 100) }; }); const subtotal = validated.reduce((sum, item) => sum + item.unitCents * item.quantity, 0); const shipping = 0; const id = crypto.randomUUID(); const orderNumber = `PAT-${Date.now().toString().slice(-8)}`; const userId = request.headers.get("oai-authenticated-user-id") ?? "local-preview"; const address = JSON.stringify({ cep: input.customer.cep, street: input.customer.street, number: input.customer.number, complement: input.customer.complement, district: input.customer.district, city: input.customer.city, state: input.customer.state });
    const statements = [env.DB.prepare(`INSERT INTO orders (id, order_number, user_id, customer_name, customer_email, customer_phone, delivery_method, address_json, payment_method, status, subtotal_cents, shipping_cents, total_cents) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending_payment', ?, ?, ?)`).bind(id, orderNumber, userId, input.customer.name, input.customer.email, input.customer.phone, input.customer.delivery, address, input.customer.payment, subtotal, shipping, subtotal + shipping), ...validated.map((item) => env.DB.prepare("INSERT INTO order_items (order_id, product_id, product_name, quantity, unit_price_cents, total_cents) VALUES (?, ?, ?, ?, ?, ?)").bind(id, item.product.id, item.product.name, item.quantity, item.unitCents, item.unitCents * item.quantity)), env.DB.prepare("DELETE FROM cart_items WHERE cart_id = ?").bind(`cart:${userId}`)];
    await env.DB.batch(statements); return Response.json({ id, orderNumber, totalCents: subtotal + shipping, paymentMode: "sandbox_pending_configuration" }, { status: 201 });
  } catch (error) { return Response.json({ error: error instanceof z.ZodError ? "Revise os dados do checkout." : "Não foi possível criar o pedido." }, { status: 400 }); }
}
